apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
  name: jwtgen-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: jwtgen.dev
    http:
      paths:
      - backend:
          service:
            name: jwtgen
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - jwtgen.dev
    secretName: jwtgen-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jwtgen
  name: jwtgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwtgen
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jwtgen
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: ghcr.io/snophey/jwtgen:main
        name: jwtgen
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: jwtgen
  name: jwtgen
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jwtgen
  type: ClusterIP
